import HeaderPage from '@/components/HeaderPage/HeaderPage'
import './globals.css'
import { Poppins } from 'next/font/google'
import Footer from '@/components/Footer/Footer'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ["100", '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata = {
  title: 'ColorQ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <HeaderPage />
        {children}
        <Footer />
      </body>
    </html>
  )
}
